#单节点
#应用名称及验证账号
server:
  port: 7900
spring:
  application:
    name: eureka
  security:
    user:
      name: root
      password: root
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    #关闭自我保护
    enable-self-preservation: false
    #清理间隔时间
    eviction-interval-timer-in-ms: 5000
    #设置服务注册中心的URL,第一个root是用户名，第二个root是密码,@后面是注册中心ip地址，这里为本地服务，所以用localhost。在 Eureka 和client 的yml 中 都必须配置！
    service-url:
      defaultZone: http://root:root@eureka-7900:7900/eureka/
  instance:
    hostname: eureka-7900
logging:
  level:
    root: info
#---
#spring:
#  profiles: 7900
#server:
#  port: 7900
#eureka:
#  client:
#    service-url:
#      defaultZone: http://root:root@localhost:7900/eureka/